#!/bin/bash -e

source builder-env
docker run -it --rm --net=host -v `pwd`:/go/src/${PROJECT_REPO} -w /go/src/$PROJECT_REPO $BUILDER_IMAGE /bin/bash -c "./builder-linkdirs && /bin/bash"

# clean up symlink
rm node_modules || :
